= Event Sourcing et CQRS

== Qu'est-ce qu'un log?

Le logging est souvent quelque chose que nous négligeons, nous, développeur. Pourtant ils s'avèrent être indispensable lorsque nous devons comprendre pourquoi l'application ne se comporte pas de la manière dont nous espérions. Nous pouvons aller voir en base de données quel est l'état du système mais bien souvent cela n'est pas suffisant. Pour les cas non triviaux, observer les données actuelles ne nous permet pas de comprendre comment et pourquoi l'état de l'application est ce qu'il est maintenant. Ce qu'il manque comment information c'est le passé. Autrement dit, la séquence des évènements qui se sont produit. C'est eux que nous espérons trouver dans nos fichiers de log, c'est eux qui nous premettront de comprendre le présent.

Ce type de logs, utilisé pour le debugging, est destiné être lu et interprété par des humains. Ils ne sont pas "programmatiquement" exploitable. Cependant, depuis des décénnies, les logs sont la pierre angulaire de nombreux systèmes. Si on abstrait le concept, un log peut être définis comme une séquence d'enregistrements ordonnés par la date à laquelle ils se sont produits. Cette séquence ne supporte que l'ajout de nouveaux enregistrements.

Un de ces systèmes nous est bien famillier, il s'agit de git. le log de git est composé d'une séquence de commits qui ont modifié les fichiers versionnés. Lorsqu'on checkout une branche, la version des fichiers sur cette branche est obtenue en appliquant séquentiellement les commits sur une version d'origine. Git est probablement le système *event sourcé* que nous utilisons le plus souvent.

== Qu'est que l'event sourcing?

L'event sourcing consiste à appliquer ce concept de log à la persistence de l'état d'une application. Au lieu d'enregistrer cet état dans des tables en base de données, on va simplement enregistrer la séquence des évènement qui ont modifié celui-ci. Lorsqu'on veut avoir l'état actuel du système, il suffit de récupérer les évènements et les appliquer à un état initial.

== Un exemple: l'issue tracker de github

Nous allons mettre ce pattern en pratique en implémentant l'issue tracker de github. Voici une liste non-exhaustive des fonctionnalités exposées par ce module:

* Soumettre une issue
* Commenter une issue
* Assigner une issue
* Catégoriser une issue
* Plannifer une issue
* Fermer une issue

Chacun de ces cas d'utilisation est détaillé dans un test unitaire associé.

Passons d'abord un moment sur un exemple de code sans event sourcing. Une `Issue` est une entité qui pourrait être représentée comme suit (cette représentation est volontairement simplifiée) :

.Issue.scala
[source,scala]
---
/**
  * Issue is an entity. It is fetched and persisted from the database using a {@link Issuetrackerrepository}.
  */
case class Issue(
  id: IssueId,
  title: String,
  author: UserId,
  status: IssueStatus,
  comments: List[String],
  assigneees: List[UserId],
  milestones: List[MilestoneId],
  labels: List[String]
)
---

La persistence de cette entité dans une base de données relationnelle va impliquer plusieurs tables et des relations entre chacunes. Une table `ISSUES`, une `MILESTONES`, une `USERS`, une `COMMENTS` et une `LABELS`. La table `ISSUES` aura des clés étrangères vers chacunes des autres. Bien que ce modèle soit intentionnellement simplifié, nous pouvons considérer qu'il soit assez proche de la réalité pour les besoin de cet exemple.

Les opérations `CRUD` de cette entité en base de données sont abtraites derrière une interface `IssueTrackerRepository`:

.Issue.scala
[source,scala]
---
/**
  * Interface for issue related database operations.
  */
trait IssueTrackerRepository {
  def nextId(): IssueId
  def persist(issue: Issue): Unit
  def update(issue: Issue): Unit
  def find(id: IssueId): Issue
}
---

Le composant qui va implémenter la logique business (le cas d'utilisation) est implémenté dans le module `IssueTracker`. Pour la création d'une nouvelle issue, ce module reçoit la commande `Submit` de l'interface utilisateur, la valide, créer une nouvelle entité, la persiste en base de données et la retourne. Une séquence d'actions classique pour une opération de création.

.Issue.scala
[source,scala]
---
def handle(submit: Submit): Issue = {
    // Validates the input parameters (author exists, repository exists and other business rules)
    // ..
    // Once validated create and issue
    val issue = Issue(
      issueTrackerRepository.nextId(),                               // <-- assigning a new issue identifier and a title and a author to this model implicitly means that a issue has been created
      submit.title,
      UserId("123"),
      Open,                                                          // <-- implicitly means the issue has been closed yet
      submit.commentO.map ((c: String) => List(c)) getOrElse List(), // <-- implicitly means the issue has been commented
      submit.assignees,                                              // <-- implicitly means the issue has been assigned
      submit.milestones,                                             // <-- implicitly means the issue has been planned
      submit.categories                                              // <-- implicitly means the issue has been categorized
    )
    // persist it
    issueTrackerRepository.persist(issue)
    // return it
    issue // <-- implicitly means all the events have been succe
  }
---

Le fait est que dans cette implémentation beaucoup d'évènements implicites ce produisent:

* créer une entité `Issue` en lui attribuant un identifiant unique, lui assignant le titre et le userId de la commande signifie que l'issue a été crée
* si un commentaire existe, cela veut dire que l'`issue` a été commentée
* si la liste des assignees n'est pas vide, cela veut dire que l'`issue` est assignée à chacun des utilisateur identifié par leur id
* si la liste des milestones n'est pas vide, cela veut dire que l'`issue` est plannifiée dans chacun des milestones identifié par leur id
* si la liste des catégorie n'est pas vide, cela veut dire que l'`issue` est catégorisée avec chacun des labels

Je considère ces évènements comme __implicites__ car ils ne sont pas matérialisés par un symbole du langage. Nulle part, il y a un type qui représente ces évènements. Ceux-ci sont cachés derrière les affectations de paramètre. L'issue, n'est que la conséquence de ces évènements. Ce n'est qu'une vue possible, une projection, une matérialisation parmis tant d'autres.

Essyons de transformer cet exemple en appliquant le pattern d'event sourcing.


== Que retenir de cet exemple ?

=== Les évènements sont des faits business

Un évènement est quelque chose qui s'est passé, c'est pour cela qu'il est une bonne pratique d'utiliser des verbes au passé. Par ailleurs, ils ont tous une signification business. Leur nom évoque des fait réels du domaine.

=== Les faits sont les faits

Une fois qu'un évènement s'est produit, il ne peut être nié, supprimé ou changé. Un évènement est immuable ainsi que le log. Le log est une structure "append only".Lorsqu'on veut corriger ce qu'il s'est produit dans le passé, on crée de nouveaux évènements.


=== L'implicite devient explicite

* tell don't ask

=== Meilleure abstraction

*

=== Plus de code

== Mais pourquoi?

=== Log on steroids & Audit trail

=== No more impedance mismatch

=== Focus on behavior

Connecte plus facile le langage business au code. 

== Pourquoi est-ce hype aujourd'hui?


== CQRS

Si nous reprenons l'issue tracker de github, à chaque fois q'une issue est assignée ça veut dire que pour la vue "issue" il a un assignée qui est ajouté à la liste. Mais ça veut dire aussi que pour la vue "progression" les chiffres sont adaptés. Ca veut dire dans la liste des issue pour un milestone, une issue en plus est ajoutée. Pour un assignee, une nouvelle issue veut dire une nouvelle entrée quelque part dans son dashboard.
